### PR TITLE
Group keys into string to be passed on HTTP_SLUG

### PR DESCRIPTION
**Pull request by stevehof**
I've tested this on our setup, but not sure if it is a valid fix. Would appreciate your thoughts?

### CODE REVIEW

**Comment by stevehof** [comment]
Just realised these will need to be made safe. Is there an ideal method that exists for that?

**Comment by stevehof** [comment]
1) I was able to fix the issue that was showing in build 63 in Travis-CI but I'm not quite sure how to run that test to indentify what e2.key() is

2) I'm not sure if my solution to slug.slug in the 2nd commit is correct, is that code identifying the keys and then placing them on the entity?

**Comment by swl10** [comment]
So you have a media resource feed with a composite key.  Are you getting an error or just having difficulty providing an appropriate hint?  Looking at the way extract_key works it will work with a string when the key is single-valued but otherwise expects an iterable with a number of items to match the number of properties in the key.  The server just extracts the slug field from the HTTP header and sends it to extract_key which dumbly iterates over it (one char at a time) most likely failing to find a valid value for each property.

I now see that you are trying to make the slug 'hint' behave just like extract_key, passing a string for a single-valued key and an iterable object for composite ones.  Perhaps the most appropriate pattern would be to create the slug hint using ODataURI.FormatKeyDict and then have the server be smart enough to unpick it from the slug.  The only issue is that, as implemented extract_key uses the literal forms for single valued keys so a slug of my-great-photo becomes a string value "my-great-photo" whereas in URI form it would need the quotes ('my-great-photo').  The brackets could be used as an indicator I guess.

Have I got the use case right?

**Comment by swl10** [comment]
Moving comments to #40

**Comment by stevehof** [comment]
Hey, so your fixes made our use case work. So it seems you did get the use case right :)

Thanks for the work!

**Pull request closed without merging**
